steps:
  # Step 1: Authenticate with Google Cloud
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["auth", "configure-docker"]

  # Step 2: Copy service account key file to Cloud Build workspace
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "/Users/jalaljanjua/Downloads/codes/My-Grocery-Backend/my-grocery-home-745726ebbfac.json",
        "/workspace/my-grocery-home-745726ebbfac.json",
      ]
  # Step 3: Copy .env file to Cloud Build workspace
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "/Users/jalaljanjua/Downloads/codes/My-Grocery-Backend/.env",
        "/workspace/.env",
      ]

  # Authenticate with service account using the copied key file
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud auth activate-service-account --key-file=/workspace/my-grocery-home-745726ebbfac.json

  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "my-grocery-app", "."]

  # Tag the image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "my-grocery-app:latest",
        "gcr.io/my-grocery-home/my-grocery-app:latest",
      ]

  # Configure docker authentication
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["auth", "configure-docker"]

  # Push the image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/my-grocery-home/my-grocery-app:latest"]

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "my-grocery-app" # Updated service name
      - "--image"
      - "gcr.io/my-grocery-home/my-grocery-app:latest"
      - "--platform"
      - "managed"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
      # Set environment variables from .env file
      - "--set-env-vars=$(cat .env | xargs)"
      - "--update-env-vars=GOOGLE_APPLICATION_CREDENTIALS=/workspace/my-grocery-home-745726ebbfac.json"

    timeout: "1600s"

images:
  - "gcr.io/my-grocery-home/my-grocery-app:latest"

timeout: "3600s"
